# -*- coding: utf-8 -*-
"""Aula 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x07nqU-eNIS3GuwUk1WL-l1PHzYAMZaS
"""

import pandas as pd

df1 = pd.read_excel("Aracaju.xlsx")
df2= pd.read_excel("Fortaleza.xlsx")
df3= pd.read_excel("Natal.xlsx")
df4 = pd.read_excel("Recife.xlsx")
df5 = pd.read_excel("Salvador.xlsx")



df = pd.concat([df1,df2,df3,df4,df5])

df.head()

df.tail()

df.sample(5)  #amostra de 5 linhas

#alterando o tipo de dados
df["LojaID"] = df["LojaID"].astype("object")

df.dtypes

df.isnull().sum()

df['Vendas'].fillna(df['Vendas'].mean(), inplace = True)  #substituir pela média os valores nulos

df.dropna(inplace = True)  #substituir os valores nulos por 0.

df.dropna(subset = ['Vendas'], inplace = True) #apagando valores nulos de uma coluna espercifica

df.dropna( how = "all", inplace = True)#apagando valores nulos de todo o arquivo

#criando novas colunas
df["RECEITA"]= df['Vendas'].mul(df['Qtde'])

df.head()

df['RECEITA'].max()

df['RECEITA'].min()

df.nlargest(3, "RECEITA")  # os maiores valores da coluna

df.nsmallest(3, "RECEITA")

df.sort_values("RECEITA", ascending=False).head(10) #mostragem do maior ao menor

# transformando a coluna de data string para int
df['Data'] = df["Data"].astype('int64')

df['Data'] = pd.to_datetime(df['Data']) #transformando em data

df.groupby(df['Data'].dt.year)['RECEITA'].sum() # receita de cada ano

df.sample(5)

#criando uma nova coluna
df['Ano de venda'] = df['Data'].dt.year # utiliza o ano da coluna data para nova coluna Ano d venda

df.sample(5)

#criando coluna com A data gerando a coluna mês
df['Mês_venda'] = df['Data'].dt.month

#criando coluna com A data gerando a coluna Dia
df['Dia_venda'] = df['Data'].dt.day

df.sample(5)

#criando coluna com A data gerando a coluna TRISMESTRE
df['Trimestre_venda'] = df['Data'].dt.quarter

df['LojaID'].value_counts(ascending = False)

df['LojaID'].value_counts(ascending = True).plot.bar()

df['LojaID'].value_counts(ascending = True).plot.barh()

df.groupby(df["Data"].dt.year)['RECEITA'].sum().plot.pie()

df['Cidade'].value_counts()

import matplotlib.pyplot as plt
df['Cidade'].value_counts().plot.bar(title = 'Total de Vendas por Cidade')
plt.xlabel("CIDADE")
plt.ylabel('TOTAL DE VENDAS')

df['Cidade'].value_counts().plot.bar(title = 'Total de Vendas por Cidade', color = 'red')
plt.xlabel("CIDADE")
plt.ylabel('TOTAL DE VENDAS')

#alterando o estilo do grafico pela pag web matplotlib
plt.style.use('ggplot')

df.groupby(df['Mês_venda'])["Qtde"].sum().plot()
plt.xlabel('MES')
plt.ylabel('TOTAL DE PRODUTOS VENDIDOS')
plt.legend()
plt.savefig("GRAFICO.png")